repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        description: "This hook checks coding style"
        language: system
        types:
          - python

      - id: autoflake
        name: autoflake
        entry: autoflake
        description: "Removes unused imports and variables"
        language: system
        types:
          - python

      - id: black
        name: black
        entry: black
        description: "The Uncompromising Code Formatter"
        language: system
        types:
          - python

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        description: "The Uncompromising Code Formatter"
        language: system
        types:
          - python
